CREATE DATABASE `NGrams`;
USE `NGrams`;
CREATE TABLE `2Grams` (
	`Index` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `Count` BIGINT NOT NULL,
    `Word1` VARCHAR(255) NOT NULL,
    `Word2` VARCHAR(255) NOT NULL,
    `Percent` DECIMAL(16,15)
);
CREATE TABLE `3Grams` (
	`Index` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `Count` BIGINT NOT NULL,
    `Word1` VARCHAR(255) NOT NULL,
    `Word2` VARCHAR(255) NOT NULL,
    `Word3` VARCHAR(255) NOT NULL,
    `Percent` DECIMAL(16,15)
);
CREATE TABLE `4Grams` (
	`Index` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `Count` BIGINT NOT NULL,
    `Word1` VARCHAR(255) NOT NULL,
    `Word2` VARCHAR(255) NOT NULL,
    `Word3` VARCHAR(255) NOT NULL,
    `Word4` VARCHAR(255) NOT NULL,
    `Percent` DECIMAL(16,15)
);
CREATE TABLE `5Grams` (
	`Index` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `Count` BIGINT NOT NULL,
    `Word1` VARCHAR(255) NOT NULL,
    `Word2` VARCHAR(255) NOT NULL,
    `Word3` VARCHAR(255) NOT NULL,
    `Word4` VARCHAR(255) NOT NULL,
    `Word5` VARCHAR(255) NOT NULL,
    `Percent` DECIMAL(16,15)
);