package ai.legendary.infrastructure;

import java.io.IOException;
import java.util.Scanner;

import javax.servlet.*;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
/*@WebServlet(
		urlPatterns = "/*"
		)*/
public class BasicServer extends HttpServlet {
	private static final long serialVersionUID = 1L;
	public void init() throws ServletException {
		System.out.println("starting...");
	}
	protected void doGet(final HttpServletRequest request, final HttpServletResponse response) throws ServletException, IOException {
		response.getOutputStream().print("Hello world!");
		response.getOutputStream().print("This was generated by the server.");
		response.getOutputStream().close();
	}
	public void close() {
		
	}

}
